export const Sounds =
  {
    "Country": "Country ident.ogg",
    "Beat": "Beat ident.ogg",
    "Reggae": "Reggae ident.ogg",
    "Serious": "Serious ident.ogg",
    "Polka": "Polka ident.ogg",
    "Charm": "charm.ogg",
    "Ding": "ding.ogg",
    "Noted": "noted.ogg",
    "Notify": "notify.ogg",
    "Random Keys": "random-keys.ogg",
    "Success": "success.ogg",
    "Wobble": "wobble.ogg",
    "Laser": "laser5.ogg",
    "Power Up": "powerUp1.ogg",
    "Re-power Up": "powerUp10.ogg",
    "Low Down": "lowDown.ogg",
    "Pep": "pepSound1.ogg",
    "Phase Jump": "phaseJump3.ogg",
    "Radar": "radar1.ogg",
    "Space Trash": "spaceTrash4.ogg",
    "Three Tone Two": "threeTone2.ogg",
    "Cards": "cardFan1.ogg",
  };
